/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PeraturanRouteImport } from './routes/peraturan'
import { Route as MateriRouteImport } from './routes/materi'
import { Route as LaporRouteImport } from './routes/lapor'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as InformasiRouteImport } from './routes/informasi'
import { Route as CekStatusRouteImport } from './routes/cek-status'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SIndexRouteImport } from './routes/s.index'
import { Route as BeritaIndexRouteImport } from './routes/berita/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as BeritaSlugRouteImport } from './routes/berita/$slug'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardStaffRouteImport } from './routes/admin/dashboard/staff'
import { Route as AdminDashboardPengaturanRouteImport } from './routes/admin/dashboard/pengaturan'
import { Route as AdminDashboardLaporanRouteImport } from './routes/admin/dashboard/laporan'
import { Route as AdminDashboardKontenRouteImport } from './routes/admin/dashboard/konten'
import { Route as AdminDashboardJadwalRouteImport } from './routes/admin/dashboard/jadwal'
import { Route as AdminDashboardBookingRouteImport } from './routes/admin/dashboard/booking'
import { Route as AdminDashboardBeritaRouteImport } from './routes/admin/dashboard/berita'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PeraturanRoute = PeraturanRouteImport.update({
  id: '/peraturan',
  path: '/peraturan',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriRoute = MateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporRoute = LaporRouteImport.update({
  id: '/lapor',
  path: '/lapor',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiRoute = InformasiRouteImport.update({
  id: '/informasi',
  path: '/informasi',
  getParentRoute: () => rootRouteImport,
} as any)
const CekStatusRoute = CekStatusRouteImport.update({
  id: '/cek-status',
  path: '/cek-status',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SIndexRoute = SIndexRouteImport.update({
  id: '/s/',
  path: '/s/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardStaffRoute = AdminDashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardPengaturanRoute =
  AdminDashboardPengaturanRouteImport.update({
    id: '/pengaturan',
    path: '/pengaturan',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardLaporanRoute = AdminDashboardLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardKontenRoute = AdminDashboardKontenRouteImport.update({
  id: '/konten',
  path: '/konten',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardJadwalRoute = AdminDashboardJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardBookingRoute = AdminDashboardBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardBeritaRoute = AdminDashboardBeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => AdminDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/cek-status': typeof CekStatusRoute
  '/informasi': typeof InformasiRoute
  '/jadwal': typeof JadwalRoute
  '/lapor': typeof LaporRoute
  '/materi': typeof MateriRoute
  '/peraturan': typeof PeraturanRoute
  '/profil': typeof ProfilRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/berita/$slug': typeof BeritaSlugRoute
  '/s/$code': typeof SCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/s/': typeof SIndexRoute
  '/admin/dashboard/berita': typeof AdminDashboardBeritaRoute
  '/admin/dashboard/booking': typeof AdminDashboardBookingRoute
  '/admin/dashboard/jadwal': typeof AdminDashboardJadwalRoute
  '/admin/dashboard/konten': typeof AdminDashboardKontenRoute
  '/admin/dashboard/laporan': typeof AdminDashboardLaporanRoute
  '/admin/dashboard/pengaturan': typeof AdminDashboardPengaturanRoute
  '/admin/dashboard/staff': typeof AdminDashboardStaffRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/cek-status': typeof CekStatusRoute
  '/informasi': typeof InformasiRoute
  '/jadwal': typeof JadwalRoute
  '/lapor': typeof LaporRoute
  '/materi': typeof MateriRoute
  '/peraturan': typeof PeraturanRoute
  '/profil': typeof ProfilRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/s/$code': typeof SCodeRoute
  '/admin': typeof AdminIndexRoute
  '/berita': typeof BeritaIndexRoute
  '/s': typeof SIndexRoute
  '/admin/dashboard/berita': typeof AdminDashboardBeritaRoute
  '/admin/dashboard/booking': typeof AdminDashboardBookingRoute
  '/admin/dashboard/jadwal': typeof AdminDashboardJadwalRoute
  '/admin/dashboard/konten': typeof AdminDashboardKontenRoute
  '/admin/dashboard/laporan': typeof AdminDashboardLaporanRoute
  '/admin/dashboard/pengaturan': typeof AdminDashboardPengaturanRoute
  '/admin/dashboard/staff': typeof AdminDashboardStaffRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/cek-status': typeof CekStatusRoute
  '/informasi': typeof InformasiRoute
  '/jadwal': typeof JadwalRoute
  '/lapor': typeof LaporRoute
  '/materi': typeof MateriRoute
  '/peraturan': typeof PeraturanRoute
  '/profil': typeof ProfilRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/berita/$slug': typeof BeritaSlugRoute
  '/s/$code': typeof SCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/s/': typeof SIndexRoute
  '/admin/dashboard/berita': typeof AdminDashboardBeritaRoute
  '/admin/dashboard/booking': typeof AdminDashboardBookingRoute
  '/admin/dashboard/jadwal': typeof AdminDashboardJadwalRoute
  '/admin/dashboard/konten': typeof AdminDashboardKontenRoute
  '/admin/dashboard/laporan': typeof AdminDashboardLaporanRoute
  '/admin/dashboard/pengaturan': typeof AdminDashboardPengaturanRoute
  '/admin/dashboard/staff': typeof AdminDashboardStaffRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/cek-status'
    | '/informasi'
    | '/jadwal'
    | '/lapor'
    | '/materi'
    | '/peraturan'
    | '/profil'
    | '/admin/dashboard'
    | '/berita/$slug'
    | '/s/$code'
    | '/admin/'
    | '/berita/'
    | '/s/'
    | '/admin/dashboard/berita'
    | '/admin/dashboard/booking'
    | '/admin/dashboard/jadwal'
    | '/admin/dashboard/konten'
    | '/admin/dashboard/laporan'
    | '/admin/dashboard/pengaturan'
    | '/admin/dashboard/staff'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/cek-status'
    | '/informasi'
    | '/jadwal'
    | '/lapor'
    | '/materi'
    | '/peraturan'
    | '/profil'
    | '/berita/$slug'
    | '/s/$code'
    | '/admin'
    | '/berita'
    | '/s'
    | '/admin/dashboard/berita'
    | '/admin/dashboard/booking'
    | '/admin/dashboard/jadwal'
    | '/admin/dashboard/konten'
    | '/admin/dashboard/laporan'
    | '/admin/dashboard/pengaturan'
    | '/admin/dashboard/staff'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/cek-status'
    | '/informasi'
    | '/jadwal'
    | '/lapor'
    | '/materi'
    | '/peraturan'
    | '/profil'
    | '/admin/dashboard'
    | '/berita/$slug'
    | '/s/$code'
    | '/admin/'
    | '/berita/'
    | '/s/'
    | '/admin/dashboard/berita'
    | '/admin/dashboard/booking'
    | '/admin/dashboard/jadwal'
    | '/admin/dashboard/konten'
    | '/admin/dashboard/laporan'
    | '/admin/dashboard/pengaturan'
    | '/admin/dashboard/staff'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  CekStatusRoute: typeof CekStatusRoute
  InformasiRoute: typeof InformasiRoute
  JadwalRoute: typeof JadwalRoute
  LaporRoute: typeof LaporRoute
  MateriRoute: typeof MateriRoute
  PeraturanRoute: typeof PeraturanRoute
  ProfilRoute: typeof ProfilRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  BeritaSlugRoute: typeof BeritaSlugRoute
  SCodeRoute: typeof SCodeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  SIndexRoute: typeof SIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peraturan': {
      id: '/peraturan'
      path: '/peraturan'
      fullPath: '/peraturan'
      preLoaderRoute: typeof PeraturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi': {
      id: '/materi'
      path: '/materi'
      fullPath: '/materi'
      preLoaderRoute: typeof MateriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lapor': {
      id: '/lapor'
      path: '/lapor'
      fullPath: '/lapor'
      preLoaderRoute: typeof LaporRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi': {
      id: '/informasi'
      path: '/informasi'
      fullPath: '/informasi'
      preLoaderRoute: typeof InformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-status': {
      id: '/cek-status'
      path: '/cek-status'
      fullPath: '/cek-status'
      preLoaderRoute: typeof CekStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/': {
      id: '/s/'
      path: '/s'
      fullPath: '/s/'
      preLoaderRoute: typeof SIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/staff': {
      id: '/admin/dashboard/staff'
      path: '/staff'
      fullPath: '/admin/dashboard/staff'
      preLoaderRoute: typeof AdminDashboardStaffRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/pengaturan': {
      id: '/admin/dashboard/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/dashboard/pengaturan'
      preLoaderRoute: typeof AdminDashboardPengaturanRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/laporan': {
      id: '/admin/dashboard/laporan'
      path: '/laporan'
      fullPath: '/admin/dashboard/laporan'
      preLoaderRoute: typeof AdminDashboardLaporanRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/konten': {
      id: '/admin/dashboard/konten'
      path: '/konten'
      fullPath: '/admin/dashboard/konten'
      preLoaderRoute: typeof AdminDashboardKontenRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/jadwal': {
      id: '/admin/dashboard/jadwal'
      path: '/jadwal'
      fullPath: '/admin/dashboard/jadwal'
      preLoaderRoute: typeof AdminDashboardJadwalRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/booking': {
      id: '/admin/dashboard/booking'
      path: '/booking'
      fullPath: '/admin/dashboard/booking'
      preLoaderRoute: typeof AdminDashboardBookingRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/berita': {
      id: '/admin/dashboard/berita'
      path: '/berita'
      fullPath: '/admin/dashboard/berita'
      preLoaderRoute: typeof AdminDashboardBeritaRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardBeritaRoute: typeof AdminDashboardBeritaRoute
  AdminDashboardBookingRoute: typeof AdminDashboardBookingRoute
  AdminDashboardJadwalRoute: typeof AdminDashboardJadwalRoute
  AdminDashboardKontenRoute: typeof AdminDashboardKontenRoute
  AdminDashboardLaporanRoute: typeof AdminDashboardLaporanRoute
  AdminDashboardPengaturanRoute: typeof AdminDashboardPengaturanRoute
  AdminDashboardStaffRoute: typeof AdminDashboardStaffRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardBeritaRoute: AdminDashboardBeritaRoute,
  AdminDashboardBookingRoute: AdminDashboardBookingRoute,
  AdminDashboardJadwalRoute: AdminDashboardJadwalRoute,
  AdminDashboardKontenRoute: AdminDashboardKontenRoute,
  AdminDashboardLaporanRoute: AdminDashboardLaporanRoute,
  AdminDashboardPengaturanRoute: AdminDashboardPengaturanRoute,
  AdminDashboardStaffRoute: AdminDashboardStaffRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  CekStatusRoute: CekStatusRoute,
  InformasiRoute: InformasiRoute,
  JadwalRoute: JadwalRoute,
  LaporRoute: LaporRoute,
  MateriRoute: MateriRoute,
  PeraturanRoute: PeraturanRoute,
  ProfilRoute: ProfilRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  BeritaSlugRoute: BeritaSlugRoute,
  SCodeRoute: SCodeRoute,
  AdminIndexRoute: AdminIndexRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  SIndexRoute: SIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
